mod ca;
mod har;
mod mitm;
mod proxy;
mod recorder;

use std::path::PathBuf;
use std::sync::Arc;

use clap::{Parser, Subcommand};
use tracing::info;

#[derive(Parser)]
#[command(
    name = "gproxy-recorder",
    about = "HTTP/SOCKS recording proxy for capturing LLM API traffic"
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate a self-signed CA certificate and private key
    InitCa {
        /// Output path for the combined PEM file (cert + key)
        #[arg(long, default_value = "gproxy-ca.pem")]
        output: PathBuf,
    },
    /// Start the recording proxy
    Record {
        /// HTTP proxy listen address
        #[arg(long, default_value = "127.0.0.1:8080")]
        listen: String,

        /// CA PEM file path (generated by init-ca)
        #[arg(long, default_value = "gproxy-ca.pem")]
        ca: PathBuf,

        /// HAR output file path
        #[arg(long, default_value = "recording.har")]
        output: PathBuf,

        /// Upstream proxy (e.g. socks5://127.0.0.1:10808)
        #[arg(long)]
        upstream_proxy: Option<String>,

        /// Only record requests to these hosts (can be repeated)
        #[arg(long)]
        filter_host: Vec<String>,
    },
}

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let cli = Cli::parse();

    match cli.command {
        Commands::InitCa { output } => match ca::generate_ca(&output) {
            Ok(()) => {
                info!("CA certificate written to {}", output.display());
                println!("CA cert: {}", output.display());
                println!("CA key:  {}.key.der", output.display());
            }
            Err(e) => {
                eprintln!("Failed to generate CA: {}", e);
                std::process::exit(1);
            }
        },
        Commands::Record {
            listen,
            ca: ca_path,
            output,
            upstream_proxy,
            filter_host,
        } => {
            let rt = tokio::runtime::Runtime::new().expect("Failed to create tokio runtime");
            rt.block_on(async move {
                run_record(listen, ca_path, output, upstream_proxy, filter_host).await;
            });
        }
    }
}

async fn run_record(
    listen: String,
    ca_path: PathBuf,
    output: PathBuf,
    upstream_proxy: Option<String>,
    filter_host: Vec<String>,
) {
    let ca = match ca::load_ca(&ca_path) {
        Ok(ca) => Arc::new(ca),
        Err(e) => {
            eprintln!("Failed to load CA from {}: {}", ca_path.display(), e);
            eprintln!("Run `gproxy-recorder init-ca` first to generate a CA certificate.");
            std::process::exit(1);
        }
    };

    let mitm = Arc::new(mitm::MitmAcceptor::new(ca));
    let recorder = Arc::new(recorder::Recorder::new(filter_host));

    let recorder_for_shutdown = Arc::clone(&recorder);
    let output_for_shutdown = output.clone();

    // Spawn shutdown handler
    let shutdown_handle = tokio::spawn(async move {
        tokio::signal::ctrl_c()
            .await
            .expect("Failed to listen for ctrl-c");
        info!("Shutting down, flushing HAR...");
        let count = recorder_for_shutdown.entry_count();
        if let Err(e) = recorder_for_shutdown.flush_to_file(&output_for_shutdown) {
            eprintln!("Failed to write HAR file: {}", e);
        } else {
            println!(
                "Wrote {} entries to {}",
                count,
                output_for_shutdown.display()
            );
        }
        std::process::exit(0);
    });

    info!("Starting recording proxy");
    if let Err(e) = proxy::run_http_proxy(listen, mitm, recorder, upstream_proxy).await {
        eprintln!("Proxy error: {}", e);
    }

    let _ = shutdown_handle.await;
}
